### ISSUE TITLE
Cannot load custom fonts

### ISSUE THREAD

**Issue by bano0o** [bano0o/shop-template#1]
i have som mistake with font css

https://github.com/bano0o/shop-template/blob/ed1aa23f1da73876cd7220433a4a599f71a2ff06/docs/assets/css/style.css#L1

**Comment by meyt** [comment]
You have wrong path for fonts, acutally your fonts is here:
`../fonts/bla-bla-bla`

Read more about issues like this: https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/
